In [2]:
# aula introdutória
# dataFrames

In [3]:
import pandas as pd 
import numpy as np

In [4]:
series = pd.Series([7, 4, 2, np.nan, 6, 9.2])

In [5]:
series

0    7.0
1    4.0
2    2.0
3    NaN
4    6.0
5    9.2
dtype: float64

In [6]:
type(series)

pandas.core.series.Series

In [7]:
# geração de datas 'ano/mes/dia'
datas = pd.date_range('20180113', periods= 20)

In [8]:
datas

DatetimeIndex(['2018-01-13', '2018-01-14', '2018-01-15', '2018-01-16',
               '2018-01-17', '2018-01-18', '2018-01-19', '2018-01-20',
               '2018-01-21', '2018-01-22', '2018-01-23', '2018-01-24',
               '2018-01-25', '2018-01-26', '2018-01-27', '2018-01-28',
               '2018-01-29', '2018-01-30', '2018-01-31', '2018-02-01'],
              dtype='datetime64[ns]', freq='D')

In [9]:
help(pd.date_range)

Help on function date_range in module pandas.core.indexes.datetimes:

date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize=False, name=None, closed=None, **kwargs) -> pandas.core.indexes.datetimes.DatetimeIndex
    Return a fixed frequency DatetimeIndex.
    
    Parameters
    ----------
    start : str or datetime-like, optional
        Left bound for generating dates.
    end : str or datetime-like, optional
        Right bound for generating dates.
    periods : int, optional
        Number of periods to generate.
    freq : str or DateOffset, default 'D'
        Frequency strings can have multiples, e.g. '5H'. See
        :ref:`here <timeseries.offset_aliases>` for a list of
        frequency aliases.
    tz : str or tzinfo, optional
        Time zone name for returning localized DatetimeIndex, for example
        'Asia/Hong_Kong'. By default, the resulting DatetimeIndex is
        timezone-naive.
    normalize : bool, default False
        Normalize start/

In [10]:
# geração de datas 'ano/mes/dia'
datas_mensal = pd.date_range('20180113', periods= 6, freq='M') # freq 'M' == mes

In [11]:
datas_mensal

DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30',
               '2018-05-31', '2018-06-30'],
              dtype='datetime64[ns]', freq='M')

In [12]:
df = pd.DataFrame(np.random.randn(20,7), index=datas, columns=list('ABCDEFG'))

In [13]:
# geração de numeros aleatórios dentro de uma distribuição normal com média == 0 e std == 1
np.random.randn(20,7) # 20 linhas e 7 colunas

array([[ 0.00742602, -0.64733041, -0.89217741, -0.29626067, -0.87195937,
         0.04164184, -1.58011999],
       [-0.97883957, -1.11342151,  0.59180738, -0.21824824,  0.60168569,
         0.09647849, -1.03404056],
       [-0.00852135, -0.78045311,  1.36852156,  1.14363119,  0.80080523,
        -0.22060034, -0.93591121],
       [-0.96072038, -1.51123201, -2.36288774, -0.20470482, -1.18047481,
        -2.55558896, -0.74245682],
       [ 0.5172756 ,  1.0573473 ,  1.2080717 ,  0.80192249, -0.41935335,
        -0.23088815, -0.83300253],
       [ 1.7591532 ,  0.28951926,  0.58476901,  0.25174862,  0.94541607,
         0.55820989,  0.11245527],
       [-0.53681505, -0.44113161,  0.36421763, -0.82599891,  0.32272484,
        -0.31927018, -1.00603017],
       [ 0.75736271,  0.0375991 ,  1.04352582,  0.91580526, -0.83543869,
        -1.11249498, -0.13495336],
       [-0.78347051, -1.71768396,  0.12273619, -1.34920666,  1.06462068,
         0.34892821,  0.41520129],
       [ 0.19760918, -1.2027

In [14]:
list('ABCDFGHI') # ['A', 'B', 'C', 'D', 'F', 'G', 'H', 'I']

['A', 'B', 'C', 'D', 'F', 'G', 'H', 'I']

In [15]:
df

A         B         C         D         E         F  \
2018-01-13  0.866267  1.197204 -0.000678 -1.042664 -0.156238  1.492330   
2018-01-14 -0.665186 -1.512458 -0.398228 -0.185221 -0.718739  0.317165   
2018-01-15  0.324711 -0.234937  0.413174 -2.245066  0.106693 -0.468488   
2018-01-16 -1.936679 -0.973833 -0.586783  0.128195  0.781076  0.404571   
2018-01-17 -1.105703 -0.789105 -0.046757  0.398148  0.242312  0.831245   
2018-01-18 -2.326421  0.063837  0.214795 -1.619631  0.563999 -0.248010   
2018-01-19 -2.845444  0.829502 -0.169730 -0.925239 -0.404741 -1.734418   
2018-01-20 -0.393580  0.553844  1.240168 -1.434952  0.289315 -0.321013   
2018-01-21 -0.459987  2.138471  0.521139 -0.527005  0.226562  0.115342   
2018-01-22 -2.035176 -0.915298  1.198461  0.840705  0.037779 -1.972656   
2018-01-23  1.884699 -1.031621 -0.529480  0.073033  1.007202  0.998385   
2018-01-24  0.513277 -0.206565  0.086337 -0.501594 -0.374111  0.067704   
2018-01-25  1.112203 -1.966333 -1.042491  0.188644  0.209860  1.066235   
2018-01-26 -1.048222  0.761766  1.133428  1.140074 -1.443016  1.558356   
2018-01-27  0.430759  0.581682  1.979434 -0.784695 -3.516432  0.699921   
2018-01-28 -0.290554  1.824841  1.170590 -0.326298 -0.961849  0.063246   
2018-01-29  0.105979 -0.225462 -0.076590  0.999273  0.619065 -1.281400   
2018-01-30 -1.222290  0.390828  0.213339  0.343642 -0.274709 -1.138794   
2018-01-31 -0.480178  0.185647  2.157916 -0.140425  0.525978  1.390284   
2018-02-01 -0.116744  1.029907  0.541602 -1.665667  0.843466 -0.124429   

                   G  
2018-01-13 -0.877594  
2018-01-14  0.215029  
2018-01-15  2.469062  
2018-01-16 -1.403575  
2018-01-17 -0.884282  
2018-01-18 -1.799239  
2018-01-19  0.024386  
2018-01-20 -0.517125  
2018-01-21  1.254959  
2018-01-22 -0.366739  
2018-01-23 -0.814094  
2018-01-24  0.450196  
2018-01-25  1.374305  
2018-01-26  0.451327  
2018-01-27 -2.695025  
2018-01-28  1.258905  
2018-01-29 -1.127764  
2018-01-30  1.544774  
2018-01-31 -1.022805  
2018-02-01  0.385376

In [16]:
df.head()

A         B         C         D         E         F  \
2018-01-13  0.866267  1.197204 -0.000678 -1.042664 -0.156238  1.492330   
2018-01-14 -0.665186 -1.512458 -0.398228 -0.185221 -0.718739  0.317165   
2018-01-15  0.324711 -0.234937  0.413174 -2.245066  0.106693 -0.468488   
2018-01-16 -1.936679 -0.973833 -0.586783  0.128195  0.781076  0.404571   
2018-01-17 -1.105703 -0.789105 -0.046757  0.398148  0.242312  0.831245   

                   G  
2018-01-13 -0.877594  
2018-01-14  0.215029  
2018-01-15  2.469062  
2018-01-16 -1.403575  
2018-01-17 -0.884282

In [17]:
df2 = pd.DataFrame(np.random.randn(20,3), index=datas, columns=['Alan', 'Marcela', 'Mario'])

In [18]:
df2.head()

Alan   Marcela     Mario
2018-01-13 -0.111495  0.479751  0.739813
2018-01-14  0.022079  0.454420 -0.783018
2018-01-15  0.166422  0.419774 -0.099949
2018-01-16 -0.108530 -0.275411  0.757549
2018-01-17  0.476428 -0.547977 -0.381493

In [19]:
# criação de dataframe com dicionario
df3 = pd.DataFrame({'A': 39,
                    'B': 'Colisão',
                    'C': pd.Timestamp('20190123'),
                    'D': pd.Series(2, index=list(range(5)), dtype='float32'),
                    'E': np.nan
                    })

In [20]:
df3

A        B          C    D   E
0  39  Colisão 2019-01-23  2.0 NaN
1  39  Colisão 2019-01-23  2.0 NaN
2  39  Colisão 2019-01-23  2.0 NaN
3  39  Colisão 2019-01-23  2.0 NaN
4  39  Colisão 2019-01-23  2.0 NaN

In [21]:
df3.dtypes

A             int64
B            object
C    datetime64[ns]
D           float32
E           float64
dtype: object

In [22]:
df2.head()

Alan   Marcela     Mario
2018-01-13 -0.111495  0.479751  0.739813
2018-01-14  0.022079  0.454420 -0.783018
2018-01-15  0.166422  0.419774 -0.099949
2018-01-16 -0.108530 -0.275411  0.757549
2018-01-17  0.476428 -0.547977 -0.381493

In [23]:
# adição de novas colunas
df2['Franscisco'] = np.random.randn(20)

In [24]:
df2['Cláudio'] = range(20)

In [25]:
df2.columns

Index(['Alan', 'Marcela', 'Mario', 'Franscisco', 'Cláudio'], dtype='object')

In [26]:
# guardando nome das colunas em uma variavel
c = df2.columns

In [27]:
c

Index(['Alan', 'Marcela', 'Mario', 'Franscisco', 'Cláudio'], dtype='object')

In [28]:
# pegando valores das linhas e colunas em um array
df2.to_numpy()

array([[-1.11495417e-01,  4.79750635e-01,  7.39813127e-01,
         8.60114539e-01,  0.00000000e+00],
       [ 2.20794639e-02,  4.54419552e-01, -7.83018141e-01,
        -1.32936111e+00,  1.00000000e+00],
       [ 1.66422484e-01,  4.19774417e-01, -9.99494432e-02,
         2.38190231e-01,  2.00000000e+00],
       [-1.08529757e-01, -2.75410759e-01,  7.57549241e-01,
        -1.79273974e-02,  3.00000000e+00],
       [ 4.76428483e-01, -5.47976771e-01, -3.81492700e-01,
         3.84162946e-01,  4.00000000e+00],
       [-1.11034565e-01,  2.35745285e-02, -5.17389390e-01,
         6.20976867e-01,  5.00000000e+00],
       [ 4.88051085e-01,  6.94314210e-02,  1.94189816e-01,
         1.19403568e+00,  6.00000000e+00],
       [ 7.30664142e-01,  2.62970552e-01,  1.32933773e+00,
         1.93929689e-01,  7.00000000e+00],
       [-5.58121830e-01,  3.72993257e-02,  1.89891759e+00,
        -1.21029208e+00,  8.00000000e+00],
       [-1.29169226e-01, -6.73884680e-01, -5.11374623e-01,
        -3.55402886e-01

In [29]:
df3.head()

A        B          C    D   E
0  39  Colisão 2019-01-23  2.0 NaN
1  39  Colisão 2019-01-23  2.0 NaN
2  39  Colisão 2019-01-23  2.0 NaN
3  39  Colisão 2019-01-23  2.0 NaN
4  39  Colisão 2019-01-23  2.0 NaN

In [30]:
df3.to_numpy()

array([[39, 'Colisão', Timestamp('2019-01-23 00:00:00'), 2.0, nan],
       [39, 'Colisão', Timestamp('2019-01-23 00:00:00'), 2.0, nan],
       [39, 'Colisão', Timestamp('2019-01-23 00:00:00'), 2.0, nan],
       [39, 'Colisão', Timestamp('2019-01-23 00:00:00'), 2.0, nan],
       [39, 'Colisão', Timestamp('2019-01-23 00:00:00'), 2.0, nan]],
      dtype=object)

In [31]:
# fazer a transposta do dataFrame(transformar colunas em linhas)
df3.T

0                    1                    2  \
A                   39                   39                   39   
B              Colisão              Colisão              Colisão   
C  2019-01-23 00:00:00  2019-01-23 00:00:00  2019-01-23 00:00:00   
D                  2.0                  2.0                  2.0   
E                  NaN                  NaN                  NaN   

                     3                    4  
A                   39                   39  
B              Colisão              Colisão  
C  2019-01-23 00:00:00  2019-01-23 00:00:00  
D                  2.0                  2.0  
E                  NaN                  NaN

In [32]:
# concatenar dataFrames
df4 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3'],
                    'E': ['E0', 'E1', 'E2', 'E3']
                    }, index=[0, 1, 2, 3])

In [33]:
df5 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7'],
                    'E': ['E4', 'E5', 'E6', 'E7']
                    }, index=[4, 5, 6, 7])

In [34]:
df6 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11'],
                    'E': ['E8', 'E9', 'E10', 'E11']
                    }, index=[8, 9, 10, 11])

In [35]:
frames = pd.concat([df4, df5, df6])

In [36]:
frames

A    B    C    D    E
0    A0   B0   C0   D0   E0
1    A1   B1   C1   D1   E1
2    A2   B2   C2   D2   E2
3    A3   B3   C3   D3   E3
4    A4   B4   C4   D4   E4
5    A5   B5   C5   D5   E5
6    A6   B6   C6   D6   E6
7    A7   B7   C7   D7   E7
8    A8   B8   C8   D8   E8
9    A9   B9   C9   D9   E9
10  A10  B10  C10  D10  E10
11  A11  B11  C11  D11  E11

In [37]:
group = frames = pd.concat([df4, df5, df6], keys=['frame1', 'frame2', 'frame3'])

In [38]:
group

A    B    C    D    E
frame1 0    A0   B0   C0   D0   E0
       1    A1   B1   C1   D1   E1
       2    A2   B2   C2   D2   E2
       3    A3   B3   C3   D3   E3
frame2 4    A4   B4   C4   D4   E4
       5    A5   B5   C5   D5   E5
       6    A6   B6   C6   D6   E6
       7    A7   B7   C7   D7   E7
frame3 8    A8   B8   C8   D8   E8
       9    A9   B9   C9   D9   E9
       10  A10  B10  C10  D10  E10
       11  A11  B11  C11  D11  E11

In [39]:
group.loc['frame2']

A   B   C   D   E
4  A4  B4  C4  D4  E4
5  A5  B5  C5  D5  E5
6  A6  B6  C6  D6  E6
7  A7  B7  C7  D7  E7

In [41]:
frames2 = df4.append(df5)

In [42]:
frames2

A   B   C   D   E
0  A0  B0  C0  D0  E0
1  A1  B1  C1  D1  E1
2  A2  B2  C2  D2  E2
3  A3  B3  C3  D3  E3
4  A4  B4  C4  D4  E4
5  A5  B5  C5  D5  E5
6  A6  B6  C6  D6  E6
7  A7  B7  C7  D7  E7